spring:
  # 应用名称
  application:
    name: provider

  # redis 配置
  redis:
    host: 192.168.182.129
    port: 6379

  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.182.129:3306/d_seckill?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource

  # dubbo配置
  dubbo:
    server: true
    registry: zookeeper://192.168.182.129:2181

# 端口号
server:
  port: 8081

# MyBatis SQL打印（方法接口所在的包）
logging:
  level:
    root: info
    com.foxandgrapes.seckill.mapper: debug
